Start.Designer.cs
Start.cs
bin/Debug/DNNQuickSite.vshost.application
bin/Debug/DNNQuickSite.vshost.exe.manifest

This pull request also provides for more clear info/warning/error messages throughout the user experience.

This requested feature is now fully functional. Closes #10

---

DNNQuickSite.csproj
Start.cs
bin/Debug/DNNQuickSite.vshost.application
bin/Debug/DNNQuickSite.vshost.exe.manifest
obj/Debug/DNNQuickSite.csproj.FileListAbsolute.txt

Application now closes upon clicking "Visit Site".

Resolves #26

---

Start.cs

Fix for Issue-136

---

Main.Designer.cs
Main.cs

Re-position Version Info and Update Styling

---

Main.cs
Properties/AssemblyInfo.cs

Increment Version Number to 1.2.0 and Update to Use Semantic Versioning

---

Main.Designer.cs
Start.Designer.cs
Start.cs

Update Block Button Links

---

Start.cs

Trim trailing slashes from Install Base Folder

---

Start.cs

Show the path of a package if it exists on the local downloads folder.
Resolves #180

Show full path to selected version download if exists

---

README.md

Update README.md to include Azure Pipelines status badge

---

CODE_OF_CONDUCT.md

Implement a CODE OF CONDUCT

---

nvQuickSite/nvQuickSite.csproj
nvQuickSite/packages.config

Update DotNetZip version

---

nvQuickSite/Controllers/VersionController.cs

Correct path to latestVersion.json

---

nvQuickSite/Start.Designer.cs
nvQuickSite/Start.cs

Replace DNN Documentation Center with the new DNN Docs

---

nvQuickSite/Main.cs
nvQuickSite/Properties/Settings.Designer.cs
nvQuickSite/Properties/Settings.settings
nvQuickSite/Start.cs
nvQuickSite/UserSettings.Designer.cs
nvQuickSite/UserSettings.cs
nvQuickSite/app.config

Opt out statistics reporting during initial install

---

data/latestVersion.json
nvQuickSite/Properties/AssemblyInfo.cs
nvQuickSite/data/latestVersion.json

Update Version to 1.3.0

---

nvQuickSiteInstaller/nvQuickSiteInstaller.vdproj

Update Installer Version to 1.3.0

---

nvQuickSite/Controllers/PackageController.cs

Correct issue with acquiring online packages and storing locally

---

nvQuickSite/Start.cs

Resolve Invalid URI issue

---

nvQuickSite/Start.cs

Update INTERNET CURRENTLY UNAVAILABLE with a more informative exception message

---

nvQuickSite/Properties/AssemblyInfo.cs
nvQuickSite/data/latestVersion.json
nvQuickSiteInstaller/nvQuickSiteInstaller.vdproj

Update version to 1.3.1 and create installer for release

---

nvQuickSite/Controllers/PackageController.cs

Resolve Error: Could not find part of path

---

nvQuickSite/Controllers/PackageController.cs
nvQuickSite/Start.cs
nvQuickSite/data/packages.json

Automate loading of DNN Platform releases via GitHub API

---

nvQuickSite/Main.cs
nvQuickSite/Properties/Settings.Designer.cs
nvQuickSite/Properties/Settings.settings
nvQuickSite/app.config

Retain settings/preferences on upgrade

---

nvQuickSite/CodePlexRSS.cs
nvQuickSite/ComboItem.cs
nvQuickSite/Controllers/PackageController.cs
nvQuickSite/Controllers/VersionController.cs
nvQuickSite/Main.cs
nvQuickSite/Models/Package.cs
nvQuickSite/Models/Version.cs
nvQuickSite/MsgBoxYesNoIgnore.cs
nvQuickSite/Program.cs
nvQuickSite/Properties/AssemblyInfo.cs
nvQuickSite/Settings.cs
nvQuickSite/Start.cs
nvQuickSite/UserSettings.cs
nvQuickSite/data/latestVersion.json
nvQuickSite/nvQuickSite.csproj
nvQuickSiteInstaller/nvQuickSiteInstaller.vdproj

Update version to 1.4.0 and create installer for release

---

.github/stale.yml

This will help keep the backlog of issues clean with actionable.

Implement stale bot

---

nvQuickSite/Start.cs

Fixes the failed download of RCs

---

nvQuickSite/Start.Designer.cs
nvQuickSite/Start.cs

Add Community Website Link

---

nvQuickSite/Start.cs

Correct DNN install file name issues with Release Candidates downloaded

---

nvQuickSite/CodePlexRSS.cs
nvQuickSite/ComboItem.cs
nvQuickSite/Controllers/DatabaseController.cs
nvQuickSite/Controllers/FileSystemController.cs
nvQuickSite/Controllers/IISController.cs
nvQuickSite/Controllers/PackageController.cs
nvQuickSite/Controllers/VersionController.cs
nvQuickSite/Main.cs
nvQuickSite/Models/Package.cs
nvQuickSite/Models/Version.cs
nvQuickSite/MsgBoxYesNoIgnore.cs
nvQuickSite/Program.cs
nvQuickSite/Settings.cs
nvQuickSite/Start.cs
nvQuickSite/UserSettings.cs
nvQuickSite/nvQuickSite.csproj

The primary purpose of this PR is to refactor the main project.  A big shout out to @valadas for his incredible guidance through this process.  Now others should be able to understand the code of this project in a much less convoluted way, thus promoting contributions to this project.
Also, copyright notices have now been updated to reflect 2020.

Refactor Project

---

nvQuickSite/Controllers/PackageController.cs
nvQuickSite/Controllers/VersionController.cs
nvQuickSite/Main.cs
nvQuickSite/Start.cs

Resolves #240 
* Added check for ability to read the latest version of nvQuickSite from GitHub
* Added check for online connectivity
* Added logic based on the online connectivity status

Add check for online connectivity and logic based on that check

---

nvQuickSite/Controllers/DatabaseController.cs
nvQuickSite/Controllers/Exceptions/DatabaseControllerException.cs
nvQuickSite/Controllers/Exceptions/FileSystemControllerException.cs
nvQuickSite/Controllers/Exceptions/IISControllerException.cs
nvQuickSite/Controllers/Exceptions/SiteExistsException.cs
nvQuickSite/Controllers/Exceptions/VersionControllerException.cs
nvQuickSite/Controllers/FileSystemController.cs
nvQuickSite/Controllers/IISController.cs
nvQuickSite/Controllers/VersionController.cs
nvQuickSite/Exceptions/ReadAndExtractException.cs
nvQuickSite/Main.cs
nvQuickSite/Start.cs
nvQuickSite/nvQuickSite.csproj

Add folders for Exceptions classes

---

nvQuickSite/Controllers/FileSystemController.cs
nvQuickSite/Controllers/IISController.cs
nvQuickSite/DeleteSiteProgress.Designer.cs
nvQuickSite/DeleteSiteProgress.cs
nvQuickSite/DeleteSiteProgress.resx
nvQuickSite/Main.Designer.cs
nvQuickSite/Start.Designer.cs
nvQuickSite/Start.cs
nvQuickSite/ViewExistingSites.Designer.cs
nvQuickSite/ViewExistingSites.cs
nvQuickSite/ViewExistingSites.resx
nvQuickSite/nvQuickSite.csproj

Allows deleting sites create by nvQuickSite togehter with the database and files and hosts file entry, etc.
Closes #256

Adds option to delete existing sites

---

nvQuickSite/Start.Designer.cs

Resolves cursor appearance issue for the View Existing Sites button

---

nvQuickSite/Properties/Settings.Designer.cs
nvQuickSite/Properties/Settings.settings
nvQuickSite/Start.Designer.cs
nvQuickSite/Start.cs
nvQuickSite/UserSettings.Designer.cs
nvQuickSite/UserSettings.cs
nvQuickSite/app.config

Add setting for enabling the ability to install local packages

---

nvQuickSite/Controllers/DatabaseController.cs
nvQuickSite/Controllers/FileSystemController.cs
nvQuickSite/Controllers/IISController.cs
nvQuickSite/Controllers/PackageController.cs
nvQuickSite/Controllers/VersionController.cs
nvQuickSite/Main.Designer.cs
nvQuickSite/Main.cs
nvQuickSite/Main.resx
nvQuickSite/Program.cs
nvQuickSite/Start.cs
nvQuickSite/UserSettings.Designer.cs
nvQuickSite/UserSettings.cs
nvQuickSite/nvQuickSite.csproj

- Adds basic logging in most crytical code paths
- Adds ability to change logging level at runtime without restarting the app
- Does not remember the log level currently between runs, this is easy to change, I was debating either to implement this or not.
- Set to log Information level so logs informational things as well as errors by default.
- Raising the level to Debug or more will log more granular information
- Logs to a dated rolling file every day and will only keep the last 30 files (cleans itself up)
- If run in Visual Studio, also logs live to the debug output
- If run in a console, will log to the console (although not yet implemented, the logging part of it is implemented), we may actually be able to simply just use this as our console output, to be tested...

Implemented logging in application

---

nvQuickSite/Program.cs
nvQuickSite/UserSettings.Designer.cs

Refine User Settings UI and fix casing for Logs folder

---

nvQuickSite/Main.cs

Move logging of user settings values to DBG instead of INF

---

nvQuickSite/Controls/Settings/UserSettings.Designer.cs
nvQuickSite/Controls/Settings/UserSettings.cs

Gives users a quick access to the logs folder.
Closes #288

Adds a link to the logs folder in the settings

---

nvQuickSite/Controllers/FileSystemController.cs
nvQuickSite/Controllers/IISController.cs
nvQuickSite/Controls/Sites/DeleteSiteProgress.cs
nvQuickSite/Start.cs

- Fixes a typo in last step
- Removes unused usings
- Adjusts file deletion logging to not log too much in default level (get's called recursifvelly)

Fixes Typo and adjust logging

---

winget/manifests/1.4.2.yaml

Add winget manifest for 1.4.2

---

nvQuickSite/Properties/AssemblyInfo.cs
nvQuickSite/data/latestVersion.json
nvQuickSiteInstaller/nvQuickSiteInstaller.vdproj

Update version number to 2.0.0

---

winget/manifests/2.0.0.yaml

Add winget manifest for 2.0.0

---

README.md

Replace basic heading with the nvQuickSite logo

Update heading for README

---

data/latestVersion.json
nvQuickSite/Properties/AssemblyInfo.cs
nvQuickSite/data/latestVersion.json

Update version number to 2.1.0

---

nvQuickSite/Controls/Sites/ViewExistingSites.Designer.cs

Change button text

---

nvQuickSite/Controls/Dialogs/MsgBoxOk.Designer.cs
nvQuickSite/Controls/Dialogs/MsgBoxYesNo.Designer.cs
nvQuickSite/Controls/Dialogs/MsgBoxYesNoIgnore.Designer.cs

Made dialog messages be able to word-wrap
Closes #315

Made dialog messages be able to word-wrap

---

nvQuickSite/Controllers/PackageController.cs
nvQuickSite/Models/Package.cs
nvQuickSite/Start.cs

Properly sorts versions instead of just alphabetically.

---

nvQuickSite/Models/Package.cs
nvQuickSite/Properties/AssemblyInfo.cs
nvQuickSite/data/latestVersion.json

Increment version and move `usings` into namespace

---

winget/manifests/2.1.1.yaml

Add v2.1.1 manifest for WinGet

---

nvQuickSite/nvQuickSite.csproj

Migrate from FxCop analyzers to .NET analyzers

---

nvQuickSite/nvQuickSite.csproj
nvQuickSiteWixInstaller/nvQuickSiteWixInstaller.wixproj

Address StyleCop and CodeAnalysis warnings

---

nvQuickSite/Properties/AssemblyInfo.cs
nvQuickSite/data/latestVersion.json

Increment version to 2.1.2 for release prep

---

nvQuickSite/Properties/AssemblyInfo.cs
nvQuickSite/data/latestVersion.json

Bumps version to 2.2.0 for next release

Bumps version to 2.2.0 for next release

---

nvQuickSite/Controllers/IISController.cs
nvQuickSite/Properties/AssemblyInfo.cs
nvQuickSite/Properties/Settings.Designer.cs
nvQuickSite/Properties/Settings.settings
nvQuickSite/Start.Designer.cs
nvQuickSite/Start.cs
nvQuickSite/app.config
nvQuickSite/data/latestVersion.json
nvQuickSite/nvQuickSite.csproj

Merge `develop` into `main` for `2.3.0` release

Merge `develop` into `main` for `2.3.0` release

---

nvQuickSite/Controllers/IISController.cs
nvQuickSite/Properties/AssemblyInfo.cs
nvQuickSite/Start.cs
nvQuickSite/data/latestVersion.json

Resolve issue creating sites when SSL is not enabled

---

nvQuickSite/Controllers/IISController.cs
nvQuickSite/Properties/AssemblyInfo.cs
nvQuickSite/data/latestVersion.json

Add certificate hash and storename to IIS binding to ensure the correct certificate

---

nvQuickSite/Controllers/IISController.cs
nvQuickSite/Properties/AssemblyInfo.cs
nvQuickSite/Start.cs
nvQuickSite/data/latestVersion.json

Merge `develop` into `main` for `2.3.2` release

Merge `develop` into `main` for `2.3.2` release

---

nvQuickSite/Controllers/PackageController.cs
nvQuickSite/Properties/AssemblyInfo.cs
nvQuickSite/data/latestVersion.json

Add Release Candidate number to package name dropdown for clarity sake

---

nvQuickSite/Controllers/IISController.cs
nvQuickSite/Controllers/PackageController.cs
nvQuickSite/Properties/AssemblyInfo.cs
nvQuickSite/data/latestVersion.json

Merge `develop` into `main` for `2.3.3` release

Merge `develop` into `main` for `2.3.3` release

---

nvQuickSite/Controllers/DatabaseController.cs

Changed use of `sp_addrolemember` stored procedure to `ALTER ROLE` SQL

---

nvQuickSite/Controllers/DatabaseController.cs

Updated db drop to place in `SINGLE_USER` mode with rollback

---

nvQuickSite/Controllers/DatabaseController.cs
nvQuickSite/Properties/Resources.Designer.cs
nvQuickSite/Properties/Settings.Designer.cs
nvQuickSite/app.config
nvQuickSite/nvQuickSite.csproj

Changed `System.Data.SqlClient` to the newer `Microsoft.Data.SqlClient` namespace

---

nvQuickSite/Controllers/PackageExtractorController.cs
nvQuickSite/Properties/AssemblyInfo.cs
nvQuickSite/Start.cs
nvQuickSite/data/latestVersion.json
nvQuickSite/nvQuickSite.csproj
nvQuickSiteWixInstaller/Product.wxs

This PR:
* Replaces `DotNetZip` and `Ionic.Zip` with `System.IO.Compression.ZipFile`.
* This involved refactoring the package extraction code into its own class controller.
* Updates the version of nvQuickSite to 2.4.0.
* Updates the installer to support the changes for the above and `Microsoft.Data.SqlClient`.
* Resolves #385

Replaced `DotNetZip` and `Ionic.Zip` with `System.IO.Compression.ZipFile`

---

nvQuickSiteWixInstaller/Product.wxs
nvQuickSiteWixInstaller/nvQuickSiteWixInstaller.wixproj

Updated Wix to v5

---

nvQuickSite/Controllers/DialogController.cs
nvQuickSite/Controls/Dialogs/MsgBoxOk.Designer.cs
nvQuickSite/Controls/Dialogs/MsgBoxOk.cs
nvQuickSite/Controls/Sites/DeleteSiteProgress.Designer.cs
nvQuickSite/Controls/Sites/DeleteSiteProgress.cs
nvQuickSite/Main.cs
nvQuickSite/Start.cs
nvQuickSite/nvQuickSite.csproj

Add new dialog features for Get Help and Report Issue when exceptions are thrown

---

nvQuickSite/Properties/AssemblyInfo.cs
nvQuickSite/data/latestVersion.json

Update version for 2.5.0 release

Update version for 2.5.0 release
